FORMAT: 1A
HOST: http://myFirstBluePrint.apiblueprint.org/

#  myBluePrint

my first blueprint API

##  Test1 [/test]

### get menu [GET]

+ Response 200 (application/json)

        [
            {
                "name" : "chicken",
                "type" : "food"
            },
            {
                "name" : "cola",
                "type" : "drink"
            }
        ]