FORMAT: 1A
HOST: http://myFirstBluePrint.apiblueprint.org/

#  myBluePrint

my first blueprint API

##  Test1 [/test]

### return hello world [GET]

+ Response 200 (application/json)

        [
            {
                "name" : "YJL",
                "type" : "predecessor"
            },
            {
                "name" : "CT",
                "type" : "brother"
            }
        ]